-- CREATE TABLE IF NOT EXISTS blog_categories (
--                                                id VARCHAR(50) PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     created_at TIMESTAMP NOT NULL
--     );