name: CI/CD Pipeline for Sentra Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./cmd/app/main.go

      - name: Test
        run: go test -v ./... -cover
        env:
          DB_USER: runner
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: test_db
          DB_SSLMODE: disable
          REDIS_DB: 0
          REDIS_ADDRESS: localhost:6379
          REDIS_PASSWORD: ""
          JWT_ACCESS_TOKEN_SECRET: test_secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sentra-backend:latest

  deploy:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Nginx config from template
        run: |
          export DOLLAR='$'
          envsubst < nginx/conf.d/default.conf.template > nginx/conf.d/nginx.conf
        env:
          AI_FACE_DETECTION_URL: ${{ secrets.AI_FACE_DETECTION_URL }}
          AI_KTP_DETECTION_URL: ${{ secrets.AI_KTP_DETECTION_URL }}
          AI_QRIS_DETECTION_URL: ${{ secrets.AI_QRIS_DETECTION_URL }}
          AI_FACE_DETECTION_WS_URL: ${{ secrets.AI_FACE_DETECTION_WS_URL }}
          AI_KTP_DETECTION_WS_URL: ${{ secrets.AI_KTP_DETECTION_WS_URL }}
          AI_QRIS_DETECTION_WS_URL: ${{ secrets.AI_QRIS_DETECTION_WS_URL }}

      - name: Prepare deploy directory on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/sentra-app/nginx/conf.d
            mkdir -p ~/sentra-app/nginx/logs

      - name: Copy Nginx config
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nginx/conf.d/nginx.conf"
          target: "~/sentra-app"
          strip_components: 0

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/sentra-app"

      - name: Create .env file
        run: |
          cat > .env <<EOL
          # Database Config
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_SSLMODE=${{ secrets.DB_SSLMODE }}
          
          # Environment config
          PRODUCTION=true
          APP_PORT=${{ secrets.APP_PORT }}
          APP_ADDR=${{ secrets.APP_ADDR }}
          
          JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
          
          # Google OAuth2
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_STATE=${{ secrets.GOOGLE_STATE }}
          
          # Redis
          REDIS_DB=${{ secrets.REDIS_DB }}
          REDIS_ADDRESS=${{ secrets.REDIS_ADDRESS }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          
          # SMTP
          SMTP_MAIL=${{ secrets.SMTP_MAIL }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          
          # AI Services URLs
          AI_FACE_DETECTION_URL=${{ secrets.AI_FACE_DETECTION_URL }}
          AI_KTP_DETECTION_URL=${{ secrets.AI_KTP_DETECTION_URL }}
          AI_QRIS_DETECTION_URL=${{ secrets.AI_QRIS_DETECTION_URL }}
          AI_FACE_DETECTION_WS_URL=${{ secrets.AI_FACE_DETECTION_WS_URL }}
          AI_KTP_DETECTION_WS_URL=${{ secrets.AI_KTP_DETECTION_WS_URL }}
          AI_QRIS_DETECTION_WS_URL=${{ secrets.AI_QRIS_DETECTION_WS_URL }}
          
          # Gemini
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL_NAME=${{ secrets.GEMINI_MODEL_NAME }}
          
          # Doku
          DOKU_CLIENT_ID=${{ secrets.DOKU_CLIENT_ID }}
          DOKU_SECRET_KEY=${{ secrets.DOKU_SECRET_KEY }}
          DOKU_IS_PRODUCTION=${{ secrets.DOKU_IS_PRODUCTION }}
          DOKU_PUBLIC_KEY=${{ secrets.DOKU_PUBLIC_KEY }}
          PASSPHRASE=${{ secrets.PASSPHRASE }}
          
          # AWS S3
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          
          # Docker image
          DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          EOL

      - name: Copy .env file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "~/sentra-app"

      - name: Copy private key for DOKU
        if: "${{ secrets.DOKU_PRIVATE_KEY != '' }}"
        run: |
          echo "${{ secrets.DOKU_PRIVATE_KEY }}" > private.key

      - name: Copy DOKU key file
        if: "${{ secrets.DOKU_PRIVATE_KEY != '' }}"
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "private.key"
          target: "~/sentra-app"

      - name: Deploy to Biznet server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/sentra-app
            docker-compose pull
            docker-compose down
            docker-compose up -d